version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/" # Racine du projet
    schedule:
      interval: "weekly" # Vérifie chaque semaine
    open-pull-requests-limit: 5
    allow:
      - dependency-type: "all" # production et dev (ex : nodemon)
