name: CI Tests

on:
  push:
    branches:
      - develop
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Cloner le code
        uses: actions/checkout@v3

      - name: Installer Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Installer dépendances
        run: npm install

      - name: Lancer les tests
        run: npm test
